### ISSUE TITLE
Possible Pin Misconfiguration for PIN_10 (daisy pin 9) in Comments 

### ISSUE THREAD

**Issue by harshnoiise** [antoinevg/daisy_bsp#10]
https://github.com/antoinevg/daisy_bsp/blob/209d938b58d2ffe0e05af96103c17aa5a0cc0391/src/pins.rs#L14
https://github.com/antoinevg/daisy_bsp/blob/209d938b58d2ffe0e05af96103c17aa5a0cc0391/src/pins.rs#L15

The code itself appears to be correct, but I think the associated comment for both lines is accidentally swapped?
I could be completely wrong bc I'm still very new to the embedded world and if so I'll close this asap! 

But based off looking at the pinout diagram, it looks like `SPI1 MISO` is `PIN_10`/`SeedPin9` and `SPI1 MOSI` is `PIN_11`/`SeedPin10` yeah? If the comments are swapped, no big deal they're just comments, but can clear up some confusion and despair like a nub like me 🥲 

[Daisy Seed Pinout Reference](https://static1.squarespace.com/static/58d03fdc1b10e3bf442567b8/t/61b102adf8965f3e1cd096fd/1638990509655/Daisy_Seed_pinout.pdf)

Spent the entire weekend trying to configure an SSD1306 display via SPI and unfortunately no luck, however it's forced me to study this codebase a lot and the pin out diagram relentlessly lmao.

**Comment by antoinevg** [comment]
My apologies for taking so long to get to this.

You are entirely correct, thank you! 

I've updated the comments to reflect this: 1ffe4e0d411d52cbbec6961998234ef5f2af25ae
